name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_FOLDER: "MLproject/employee_churn_data_preprocessing"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow
      - name: Run mlflow project
        run: |
          mlflow run MLProject --env-manager=local
      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/models/*/ | head -n 1 | cut -d'/' -f4)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"
      - name: Save mlruns to repo
        run: |
          git config --global user.name ${{ secrets.username }}
          git config --global user.email ${{ secrets.email }}
          git add mlruns
          git commit -am "save commit and push from CI run"
          git push origin main
      - name: Build Docker Model
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "employee_churn_rf" 
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Tag Docker Image
        run: |
          docker tag employee_churn_rf ${{ secrets.DOCKER_HUB_USERNAME }}/employee_churn_rf:latest
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/employee_churn_rf:latest
